### ISSUE TITLE
Faild tests

### ISSUE THREAD

**Issue by hirocaster** [cloudspannerecosystem/pgadapter#4]
I just try this.
But failed tests.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.google.cloud.spanner.pgadapter.MetadataTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.478 s - in com.google.cloud.spanner.pgadapter.MetadataTest
[INFO] Running com.google.cloud.spanner.pgadapter.ProtocolTest
[MockitoHint] ProtocolTest.testParseMessageWorksIfNameIsEmpty (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at com.google.cloud.spanner.pgadapter.ProtocolTest.testParseMessageWorksIfNameIsEmpty(ProtocolTest.java:327)

[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.72 s - in com.google.cloud.spanner.pgadapter.ProtocolTest
[INFO] Running com.google.cloud.spanner.pgadapter.ConverterTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.google.cloud.spanner.pgadapter.ConverterTest
[INFO] Running com.google.cloud.spanner.pgadapter.StatementTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.222 s - in com.google.cloud.spanner.pgadapter.StatementTest
[INFO] Running com.google.cloud.spanner.pgadapter.PSQLTest
[MockitoHint] PSQLTest.testEscapes (see javadoc for MockitoHint):
[MockitoHint] 1. Unused -> at com.google.cloud.spanner.pgadapter.PSQLTest.setup(PSQLTest.java:65)
[MockitoHint] 2. Unused -> at com.google.cloud.spanner.pgadapter.PSQLTest.setup(PSQLTest.java:66)
[MockitoHint] 3. Unused -> at com.google.cloud.spanner.pgadapter.PSQLTest.setup(PSQLTest.java:67)
[MockitoHint] 4. Unused -> at com.google.cloud.spanner.pgadapter.PSQLTest.setup(PSQLTest.java:68)
[MockitoHint] 5. Unused -> at com.google.cloud.spanner.pgadapter.PSQLTest.setup(PSQLTest.java:71)

[INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.173 s - in com.google.cloud.spanner.pgadapter.PSQLTest
[INFO] Running com.google.cloud.spanner.pgadapter.ParserTest
[ERROR] Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.026 s <<< FAILURE! - in com.google.cloud.spanner.pgadapter.ParserTest
[ERROR] testTimestampParsing(com.google.cloud.spanner.pgadapter.ParserTest)  Time elapsed: 0.008 s  <<< FAILURE!
java.lang.AssertionError:

Expected: is [<49>, <57>, <57>, <56>, <45>, <48>, <57>, <45>, <48>, <52>, <32>, <48>, <56>, <58>, <48>, <48>, <58>, <48>, <48>, <46>, <48>]
     but: was [<49>, <57>, <57>, <56>, <45>, <48>, <57>, <45>, <48>, <52>, <32>, <50>, <49>, <58>, <48>, <48>, <58>, <48>, <48>, <46>, <48>]
        at com.google.cloud.spanner.pgadapter.ParserTest.validate(ParserTest.java:63)
        at com.google.cloud.spanner.pgadapter.ParserTest.testTimestampParsing(ParserTest.java:191)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ParserTest.testTimestampParsing:191->validate:63
Expected: is [<49>, <57>, <57>, <56>, <45>, <48>, <57>, <45>, <48>, <52>, <32>, <48>, <56>, <58>, <48>, <48>, <58>, <48>, <48>, <46>, <48>]
     but: was [<49>, <57>, <57>, <56>, <45>, <48>, <57>, <45>, <48>, <52>, <32>, <50>, <49>, <58>, <48>, <48>, <58>, <48>, <48>, <46>, <48>]
[INFO]
[ERROR] Tests run: 82, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.518 s
[INFO] Finished at: 2020-04-10T20:54:35+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project google-cloud-spanner-pgadapter: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/hirocaster/src/github.com/cloudspannerecosystem/pgadapter/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by j-clap** [comment]
Hi hirocaster,

Can you specify your test run command and environment variables? I can't seem to replicate the failure.

**Comment by j-clap** [comment]
Nevermind, I figured out the issue - it is because of how Timestamp handles toString: because of its inheritance from Date, it automatically sets the timezone to the user's timezone. The test did not account for this but will when this PR gets accepted: https://github.com/cloudspannerecosystem/pgadapter/pull/6
